authuser仕様への変更、favoボタンコンポーネントの切り出し、お気に入り判定関数の切り出し
ChiharuShinohara/FrontendStudy pull request #12
Opened 2022-01-17 02:38 UTC by ChiharuShinohara

１　HeaderNavとLoginModalについては、AuthUser stateを作ったことによる仕様の修正が入っています。
２　favoriteボタンコンポーネントの切り出しを行いました。
３　お気に入り判定関数の切り出しを行いました（favoinspection(）)。

* favoriteflagステートについては、これから変更を行う予定です。

2022-01-17 05:38 UTC, mayukosano-o commented on 6_recipe_smp/app/components/favorite/favobutton.module.scss
> +        font-size: large;
font-sizeは14px、16pxなどか、vw、rem emなどの単位を使って書いたほうが吉（他の人かぱっと見わからないため）
（ただし実際のNadiaプロジェクトだと、サイト共通指定となるためpx指定とかはしないこともありそう）

2022-01-17 05:39 UTC, mayukosano-o commented on 6_recipe_smp/app/components/favorite/favobutton.module.scss
> +
空白行は意味深なのでなるべく消しとくと吉

2022-01-17 07:20 UTC, TakutoEto requested changes
一部修正願います！

2022-01-21 00:13 UTC, ChiharuShinohara commented
cssの修正と、関数の型定義の追加を行いました

2022-01-21 00:28 UTC, TakutoEto requested changes
一部確認

2022-01-21 00:28 UTC, TakutoEto commented on 6_recipe_smp/app/components/favorite/favobutton.module.scss
> +}
こちら先の佐野さんレビューの内容反映されてる？？

2022-01-21 00:34 UTC, TakutoEto approved these changes
おｋ

2022-01-21 00:35 UTC, merged