6 recipe smp
ChiharuShinohara/FrontendStudy pull request #2
Opened 2021-11-12 00:40 UTC by ChiharuShinohara

レシピ詳細ページの作成と、お気に入りボタンを追加しました

2021-11-12 00:55 UTC, TakutoEto requested changes
一旦レビュー

2021-11-12 00:55 UTC, TakutoEto commented on 6_recipe_smp/app/＠types/basicdata.ts
> +
TypeScript型定義はパスカルケースで
https://typescript-jp.gitbook.io/deep-dive/styleguide#taipu

型とメンバーの命名はDBに紐づいているとブレがなくなる
テーブル名がrecipesだったら RecipeDataなど

2021-11-12 00:55 UTC, TakutoEto commented on 6_recipe_smp/initdb/create_table_recipes.sql
> +(recipeid serial ,
テーブルで一意になるidはrecipeidでなく`id`で良いよ！(慣例的に)

2021-11-12 00:55 UTC, TakutoEto commented on 6_recipe_smp/initdb/create_table_users.sql
> +(userid serial,
こちらも

2021-11-12 00:55 UTC, TakutoEto commented on 6_recipe_smp/app/pages/mypage/[recipeid].tsx
> +    console.log(res.data, 'serversidepropssssssssssssssssss');
これはなんだ...

2021-11-12 02:06 UTC, TakutoEto requested changes
修正点を追加

2021-11-12 02:06 UTC, TakutoEto commented on 6_recipe_smp/app/pages/api/data.ts
> +};
今回の場合「レシピ詳細情報を返すAPI」という内容だと思うので
レスポンスはテーブル毎のデータではなく、取得したデータを構造的にまとめた形が望ましい。

取得した後にデータを整形する処理を加えてリターンする。

2021-11-12 02:06 UTC, TakutoEto commented on 6_recipe_smp/app/pages/mypage/[recipeid].tsx
> +    return { props: { basicData: res.data.basicData, ingredientData: res.data.ingredientData, processData: res.data.processData } };
API設計を変更し、ここではサーバー側でまとめられた「レシピ詳細情報」のみを返すようにする

2021-11-12 07:19 UTC, TakutoEto requested changes
一部修正お願いします！

2021-11-12 07:19 UTC, TakutoEto commented on 6_recipe_smp/app/components/main/ingredients/Ingredients.tsx
> +        })}
map等でjsxを返す場合、Reactが要素を識別するためのkeyを与えないとコンソールに警告が出る(はず？)
DOM更新が発生する時にバグが起きる可能性があるため注意...
参考：https://ja.reactjs.org/docs/lists-and-keys.html

2021-11-12 07:19 UTC, TakutoEto commented on 6_recipe_smp/app/components/main/process/Process.tsx
> +         })}
こちらも

2021-11-12 07:45 UTC, TakutoEto approved these changes
おｋ！

2021-12-03 02:00 UTC, mayukosano-o commented on 6_recipe_smp/app/components/main/home/homecontainer.module.scss
> +  display: flex;
wapperにflex-boxを適用して、columnにして縦に並べていると思いますが、これはなくてもいいかもしれません（SMP用のテンプレのため、必ず縦並びだから）。意図して入れているならこのままで大丈夫です！👌

2021-12-03 02:01 UTC, mayukosano-o commented on 6_recipe_smp/app/components/main/conteiner.tsx
> +                    <p>{recipeData.recipe_name}</p>
ここはh1にしといたらいいかも

2021-12-13 05:40 UTC, mayukosano-o commented on 6_recipe_smp/app/components/main/conteiner.tsx
>                      <p>{recipeData.recipe_name}</p>
わかりにくくてごめんなさい！
<div className={style.title} >ではなく、
 <p>{recipeData.recipe_name}</p> の pをh1 にした方がいいなと思います。
調理時間とかはいまのところh1ではないので〜！

2021-12-13 05:48 UTC, merged