コンフリクトの解消
ChiharuShinohara/FrontendStudy pull request #7
Opened 2021-12-13 06:11 UTC by ChiharuShinohara

2021-12-13 06:29 UTC, ChiharuShinohara commented
・ログインユーザーの情報を、contextで管理する仕様に変更しました。
・サイトを訪れたユーザーのクッキー情報を獲得し、tokenの検証を行う仕様を追加しました。
　　tokenが一致した場合、ユーザー情報が帰ってきてuserInfoにセットされます。
　　リダイレクトしてもログイン状態は保持される仕様に変更しました。
・ログアウト機能を作成しました。（ログアウトするとクッキーの情報が削除されます）
・ログインユーザーがレシピをお気に入りしているかどうかを判定するAPIを作成しました。（途中です）

2021-12-13 07:01 UTC, TakutoEto requested changes
色々バグありそう

2021-12-17 02:59 UTC, ChiharuShinohara commented on 6_recipe_smp/app/components/userprovider/AuthUser.tsx
> +});
userInfoとsetUserInfoを別のコンテクストプロバイダーで管理する仕様に変更しました。初期値はどちらもundefinedで設定しました。

2021-12-17 02:59 UTC, ChiharuShinohara commented on 6_recipe_smp/app/modules/tokenInspection.ts
> +            }
修正しました

2021-12-17 03:58 UTC, ChiharuShinohara commented on 6_recipe_smp/app/modules/tokenInspection.ts
> +        const userinfo=res.data.data[0]
try,catchの処理を追加しました。

2021-12-20 02:28 UTC, ChiharuShinohara commented on 6_recipe_smp/app/pages/index.tsx
> +      }
context のデータ構造に、nullを追加いたしました。

2021-12-20 02:38 UTC, ChiharuShinohara commented on 6_recipe_smp/app/pages/api/token.ts
> +  };
tokenが入ってきた場合のみsqlを実行する仕様に変更しました。

2021-12-20 02:38 UTC, ChiharuShinohara commented on 6_recipe_smp/app/pages/logout.tsx
> +    useEffect( ()=>{router.push("/"); })
修正いたしました

2021-12-20 02:38 UTC, ChiharuShinohara commented on 6_recipe_smp/app/pages/mypage/[recipeid].tsx
> +      }
修正いたしました。

2021-12-20 03:45 UTC, TakutoEto requested changes
一部修正

2021-12-20 03:45 UTC, TakutoEto commented on 6_recipe_smp/app/pages/index.tsx
> +      if(authUser==undefined){
undefinedの判定はtype ofで

2021-12-20 03:45 UTC, TakutoEto commented on 6_recipe_smp/app/pages/mypage/[recipeid].tsx
> +      if(authUser==undefined){
同じく

2021-12-20 03:45 UTC, TakutoEto commented
- undefined判定箇所を直す
- 未使用コードは消す

2021-12-20 04:41 UTC, ChiharuShinohara commented on 6_recipe_smp/app/pages/index.tsx
> +      if(authUser==undefined){
修正いたしました

2021-12-20 04:41 UTC, ChiharuShinohara commented on 6_recipe_smp/app/pages/mypage/[recipeid].tsx
> +      if(authUser==undefined){
修正いたしました

2021-12-20 04:58 UTC, TakutoEto approved these changes
おｋ

2021-12-20 04:58 UTC, merged